<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete_1</name>
   <tag></tag>
   <elementGuidId>2d2d479b-6311-488f-b99a-b170923e2d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-click = 'deleteCust(cust)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[ng-click=&quot;deleteCust\(cust\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d84d3e2e-2550-4c2f-bd6b-e92a7d8a362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>deleteCust(cust)</value>
      <webElementGuid>c368f758-77b5-4b77-9be4-adcdd16fbd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>ef280a51-35ba-4c1d-97f8-721a023db9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-35d9970c429bfbd8a632753e52217331</value>
      <webElementGuid>d0a4eedd-2377-4c12-8eed-9bcb8ecdd3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@ng-click = 'deleteCust(cust)']</value>
      <webElementGuid>c117c899-c9e2-47ed-be6e-406089251fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@ng-click = 'deleteCust(cust)']</value>
      <webElementGuid>acd79536-63cf-412e-9af0-ea6d1e1f5040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>437a9ffa-6b5d-4e95-81e2-b4c60e48c3e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
