<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__</name>
   <tag></tag>
   <elementGuidId>263ad737-7fa0-4fef-bc2e-4e43dec311b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[ng-click=&quot;scrollRight\(\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-click = 'scrollRight()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2894a98d-6b49-43e7-acba-edce1305ae26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>fd23d659-3b94-45dc-b33e-b9a052750a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>1f6dc027-b9e5-42bd-b1c7-83607575fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>scrollRight()</value>
      <webElementGuid>eeece183-e235-4aeb-8b81-eff4221dcbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>a7b412d0-57d9-469d-914e-0f6064201c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7da881cd57f190ab7c92dfa21916ce2d</value>
      <webElementGuid>ba0633ac-8f84-48ba-ab06-6bbbddc387d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@ng-click = 'scrollRight()']</value>
      <webElementGuid>162d8e5f-dbab-42d8-99fc-85240c98a4b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@ng-click = 'scrollRight()']</value>
      <webElementGuid>6a476008-8030-4786-9c02-6b085425ac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '>' or . = '>')]</value>
      <webElementGuid>26861cc5-eaaa-496d-8859-c9ad5383281c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
