<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__</name>
   <tag></tag>
   <elementGuidId>1bd404e7-01d8-4070-97be-ff1ba1d19b99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.fixedBottomBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedBottomBox ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8783f7fb-df90-4cdb-ba26-4ade294f1e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>showDate</value>
      <webElementGuid>fc5c950c-0705-4553-bf99-06e6d05fff3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixedBottomBox</value>
      <webElementGuid>7a5d80bf-308f-4e14-bcd9-b99315fd0055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
&lt;
Top
>
</value>
      <webElementGuid>110c70f7-c610-46a8-9069-3dbd40eea429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5cfa9ea6c23add8d3c7c969999cde45e</value>
      <webElementGuid>d62b5c78-25a4-495e-9541-e8d8a86589ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedBottomBox ')]</value>
      <webElementGuid>b7c01363-73ce-4ff8-b954-709be24b3d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fixedBottomBox ')]</value>
      <webElementGuid>aeb60bf5-9f33-4852-98bd-61b384887d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
&lt;
Top
>
' or . = '
&lt;
Top
>
')]</value>
      <webElementGuid>9d4e2c40-a595-4e20-b454-01ba54143e6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
