<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_currency</name>
   <tag></tag>
   <elementGuidId>9eccf1c6-d204-4f8a-b773-550407897d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'currency']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>efa421f5-0d4c-436d-a1f3-35d49aa64157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>0bc61a50-8d6f-4699-bcc8-577a159a8730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>5121b99a-928f-4a9b-8536-cb7d508d1f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>4e32e36f-e8f1-43b7-b864-101e26ca14d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>3306bfbd-2300-4e63-877f-ec7a76855024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	</value>
      <webElementGuid>9365b4d3-07cb-4540-b48f-3a9edcff8101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e1c0eb23d443eb950ab0f67aef3ea842</value>
      <webElementGuid>a24d8db0-e39c-4fdd-b9e1-e818f2403add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'currency']</value>
      <webElementGuid>52d74afb-dcbb-42ef-b17e-d044f0c318cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'currency']</value>
      <webElementGuid>a3a87628-7aca-4359-94c2-a192d2e7472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	' or . = '
	      		---Currency--- 
	      		Dollar
	      		Pound 
	      		Rupee
	    	')]</value>
      <webElementGuid>1a70a8e7-f2c6-4a52-9584-e4467df4b481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
