<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Amount to be Withdrawn _</name>
   <tag></tag>
   <elementGuidId>ed2edeef-70e4-4f4a-8ad4-d415e903cf10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cda77235-4295-4990-8395-2f343a0c3716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount to be Withdrawn :</value>
      <webElementGuid>141d825f-1e81-4865-9470-636223a3b751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d0157c686ed14407de7cc7008e22344d</value>
      <webElementGuid>2d4e5fc3-4f9a-44cb-955c-d4de186af8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>0ffa735e-5041-4538-86eb-bb415957e91f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>89dfcd2c-c70e-4aef-87f3-12e829fe926d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Amount to be Withdrawn :' or . = 'Amount to be Withdrawn :')]</value>
      <webElementGuid>0280fd00-fe48-4da6-96f8-44d502c193be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
