<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_5096</name>
   <tag></tag>
   <elementGuidId>e5842dee-148c-404b-bbcd-e9a305998cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-binding ') and (name() = 'strong') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong.ng-binding:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>a8677393-7276-44ea-b39b-fd6d469642b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>5f5e2416-0f30-46f8-a7e1-806b100ed44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5096</value>
      <webElementGuid>857b1663-28f1-4e88-9f6e-021a41ce6483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-633e50c3e3c1bfa8b1050e6b6d98f5d5</value>
      <webElementGuid>ce88055b-f6d7-4c1b-9512-46e906bdd3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-binding ') and (name() = 'strong') and (position() = 2)]</value>
      <webElementGuid>94c655d9-a9c8-4a8b-8939-f40c182d08a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-binding ') and (name() = 'strong') and (position() = 2)]</value>
      <webElementGuid>76feda0e-74c1-4a74-ae0c-ec96e917a95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '5096' or . = '5096')]</value>
      <webElementGuid>d0cf12a9-627c-4b67-b615-2e1c2c77deb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
