<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_yyyy-MM-ddTHH_mm_ss_1</name>
   <tag></tag>
   <elementGuidId>5d62d4c0-fbcb-4fa8-8bf9-8207c62d6fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'end']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc0f0476-7667-42ac-8eb6-ef2038af23ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>d54140c2-74f4-4c16-a7ee-2b81b30dcd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>c2325764-6ab2-4087-ad11-f5b1b7908c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>3375f1da-d2de-4782-a5ba-efe60cb6b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>854c2da0-5e0c-4335-934a-9f1a97d203a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-MM-ddTHH:mm:ss</value>
      <webElementGuid>1a0b7d6a-19bc-4ff5-bdd2-58d546f72496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2015-01-01T00:00:00</value>
      <webElementGuid>00912e08-8442-4b77-99ac-d14156567a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-02-12T13:34:39</value>
      <webElementGuid>6e1d3c0e-0a7a-4194-a713-8eb8be2544a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-min ng-valid-max ng-valid-required</value>
      <webElementGuid>3a4d1154-3505-428e-bdd5-784a932a7bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-42aadc45f00784917f9f0b7cdcafaf04</value>
      <webElementGuid>4dff6256-2f83-478f-95d8-4d47555da495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'end']</value>
      <webElementGuid>2c4e73a7-3923-4c70-bf43-d3ef37506de3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'end']</value>
      <webElementGuid>3d595f47-b95e-4be1-916f-07490a9290ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'datetime-local' and @id = 'end' and @name = 'end' and @placeholder = 'yyyy-MM-ddTHH:mm:ss']</value>
      <webElementGuid>f8dc5402-0da8-44e4-b67a-f813323abe89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
