<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_yyyy-MM-ddTHH_mm_ss</name>
   <tag></tag>
   <elementGuidId>0325567e-77eb-4f33-95d7-e177a7107834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'start']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a98042ac-694d-401e-9c0e-f17b2fb026ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>079770a7-694e-48d4-b60e-b3b06218913f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>6c2106f8-54ca-4807-8419-50331f2eeb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>40c0e1b1-6d61-49fd-9c71-7343bceac0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>f0150b93-05e1-4cf0-90c7-8fa326555276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-MM-ddTHH:mm:ss</value>
      <webElementGuid>d55990ba-9bf5-4b87-ba1a-d160a1cb67e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2015-01-01T00:00:00</value>
      <webElementGuid>f5363bcf-b839-486a-a491-0a3aad13948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2015-07-28T00:00:00</value>
      <webElementGuid>64dab43f-1bd7-4221-8bdb-93e5787d4b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-min ng-valid-max ng-valid-required</value>
      <webElementGuid>372b1c8a-9745-479d-aa51-71212416b76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c61534f1b74f302587f26e0023b9a648</value>
      <webElementGuid>32986031-2603-4c9b-9e5d-56b9c9951d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'start']</value>
      <webElementGuid>a1f46d29-e589-4437-8bae-789ab77b613d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'start']</value>
      <webElementGuid>36bf702e-2275-42a7-b82b-ca4d8ddce06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'datetime-local' and @id = 'start' and @name = 'start' and @placeholder = 'yyyy-MM-ddTHH:mm:ss']</value>
      <webElementGuid>59b780d8-140f-4d4b-947e-a1b22fb19d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
